
metadata-file: ${.}/info.yaml

# # possible to define higher-lvl defaults that this will override
# defaults:
#   - defsA
#   - defsB

from: markdown
standalone: true

data-dir:
  ${.}/resources/pandoc

# shift-heading-level-by: -1

citeproc: true
cite-method: citeproc
bibliography: ${.}/resources/biblio.bib


#csl: resources/asme.csl  # <-- uncomment and add .csl for citation style

# for the logo, etc.
